"""Core smoke test for the ChArUco detection pipeline.

Both rendering the board and detecting it run inside isolated subprocesses
(camera_calibration.isolation.run_isolated). If this OpenCV build segfaults
here -- the reported OpenCV 4.6 problem -- the subprocess dies but this
pytest process does not: the test fails with a clear, actionable message
instead of taking the whole test run down.

No camera or robot is touched anywhere in this file.
"""
from pathlib import Path

import pytest

from camera_calibration.config import BoardConfig, load_config
from camera_calibration.isolation import run_isolated

TEST_DPI = 96
REPO_ROOT = Path(__file__).resolve().parents[2]
# Package dir itself (tests/..), not "REPO_ROOT / 'camera_calibration'" --
# the package directory is not named camera_calibration everywhere it's
# deployed (e.g. it's mh5_zed_calibration on cyc-server).
PACKAGE_ROOT = Path(__file__).resolve().parents[1]
A2_CONFIG_PATH = PACKAGE_ROOT / "configs" / "board_config_a2.yaml"


def _render(cfg: BoardConfig):
    return run_isolated(
        "camera_calibration.board_generator",
        "render_board_png",
        args=(cfg,),
        kwargs={"dpi": TEST_DPI},
        timeout=30.0,
    )


def _detect(image, cfg: BoardConfig):
    return run_isolated(
        "camera_calibration.detector",
        "detect_in_subprocess",
        args=(image, cfg.to_dict()),
        timeout=30.0,
    )


def _fail_with_diagnostics(context: str, result) -> None:
    from camera_calibration.diagnose import collect_diagnostics, format_report

    report = format_report(collect_diagnostics())
    pytest.fail(
        f"{context} did not complete cleanly (status={result.status}): {result.error}\n\n{report}"
    )


@pytest.fixture(scope="module")
def synthetic_board():
    cfg = BoardConfig()
    result = _render(cfg)
    if not result.ok:
        _fail_with_diagnostics("Board rendering", result)
    return cfg, result.value


def test_detect_markers_and_corners_on_synthetic_board(synthetic_board):
    cfg, img = synthetic_board
    result = _detect(img, cfg)
    if not result.ok:
        _fail_with_diagnostics("Detection", result)

    value = result.value
    assert value["num_markers"] > 0, "expected at least one ArUco marker detected"
    assert value["num_charuco_corners"] > 0, "expected at least one ChArUco corner interpolated"
    # A perfectly rendered, undistorted synthetic image should find (close to)
    # every corner; a generous lower bound avoids flakiness from renderer
    # differences across OpenCV versions while still catching real breakage.
    assert value["num_charuco_corners"] >= cfg.num_internal_corners // 2


@pytest.fixture(scope="module")
def synthetic_a2_board():
    try:
        cfg = load_config(A2_CONFIG_PATH)
    except ModuleNotFoundError:
        pytest.skip("pyyaml not installed")
    result = _render(cfg)
    if not result.ok:
        _fail_with_diagnostics("A2 board rendering", result)
    return cfg, result.value


def test_detect_markers_and_corners_on_synthetic_a2_board(synthetic_a2_board):
    """Same smoke test as test_detect_markers_and_corners_on_synthetic_board,
    but for the independent A2 board config (configs/board_config_a2.yaml,
    DICT_5X5_100, 10x8 squares, legacy_pattern=False)."""
    cfg, img = synthetic_a2_board
    result = _detect(img, cfg)
    if not result.ok:
        _fail_with_diagnostics("A2 detection", result)

    value = result.value
    assert value["num_markers"] > 0, "expected at least one ArUco marker detected"
    assert value["num_charuco_corners"] > 0, "expected at least one ChArUco corner interpolated"
    assert value["num_charuco_corners"] >= cfg.num_internal_corners // 2


def test_a2_board_rejects_wrong_dictionary(synthetic_a2_board):
    """Control test: detecting the A2 (DICT_5X5_100) board image with the
    5x7 board's dictionary (DICT_6X6_250) must find no markers at all --
    this is what proves detections above are dictionary-specific rather
    than an overly permissive detector, and is also why the original probe
    run against the 5x7 config (DICT_6X6_250) found markers=0 on the real
    camera frames of this A2 board."""
    cfg, img = synthetic_a2_board
    wrong_cfg = BoardConfig.from_dict({**cfg.to_dict(), "dictionary": "DICT_6X6_250"})
    result = _detect(img, wrong_cfg)
    if not result.ok:
        _fail_with_diagnostics("A2 wrong-dictionary control detection", result)

    value = result.value
    assert value["num_markers"] == 0, "wrong dictionary must not match any markers"
    assert value["num_charuco_corners"] == 0


@pytest.mark.parametrize("candidate_name", [
    "ChArUco_Board_5x7_30mm.png",
])
def test_detect_on_existing_repo_board_image_if_present(candidate_name):
    """Best-effort check against the board image already sitting in the repo
    root (generated by the legacy generate_calibration_boards.py). Skips
    cleanly if that file isn't there -- this repo isn't guaranteed to have
    it, and this test must never generate/print anything itself."""
    import cv2

    image_path = REPO_ROOT / candidate_name
    if not image_path.exists():
        pytest.skip(f"{candidate_name} not found in repo root; nothing to check")

    img = cv2.imread(str(image_path))
    if img is None:
        pytest.skip(f"cv2.imread could not read {image_path}")

    cfg = BoardConfig()  # matches the geometry baked into the legacy script
    result = _detect(img, cfg)
    if not result.ok:
        _fail_with_diagnostics(f"Detection on {candidate_name}", result)

    value = result.value
    assert value["num_markers"] > 0
    assert value["num_charuco_corners"] > 0
